code --install-extension alexanderte.dainty-vscode
code --install-extension bitburner.bitburner-vscode-integration
code --install-extension Catppuccin.catppuccin-vsc
code --install-extension connor4312.codesong
code --install-extension dtoplak.vscode-glsllint
code --install-extension eamodio.gitlens
code --install-extension EricCheng.codesongClear
code --install-extension fkrull.gtk-dark-titlebar
code --install-extension george-alisson.html-preview-vscode
code --install-extension icrawl.discord-vscode
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension mcu-debug.debug-tracker-vscode
code --install-extension mcu-debug.memory-view
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.hexeditor
code --install-extension PKief.material-icon-theme
code --install-extension slevesque.shader
code --install-extension twxs.cmake
code --install-extension vadimcn.vscode-lldb
code --install-extension yzhang.markdown-all-in-one
